In [ ]:
## Function coefficients {a3, a2, a1, a0}
## Enter the coefficients as an array, then we compute for elements a in Z_n
## Z_n = {0, 1, 2, ... , n-1}
## 2D array: 
## R1         (a[0]*Z_n[0]^3 + a[1]*Z_n[0]^2 + a[2]*Z_n[0] + a[3])modn          
## R2         (a[0]*Z_n[1]^3 + a[1]*Z_n[1]^2 + a[2]*Z_n[1] + a[3])modn 
##             ...
##             ...
## Rn         (a[0]*Z_n[n-1]^3 + a[1]*Z_n[n-1]^2 + a[2]*Z_n[n-1] + a[3])modn 
##
##
## For all R[i], compute result(modn) and check
## If result(modn) == 0 for any Ri then reducible
## Elif result(modn) != 0 for all Ri, then irreducible

In [ ]:
"""
Take polynomial of degree 4: 

a4x^4 + a3x^3 + a2x^2 + a1x + a0

"""
from itertools import product

# Define the field Z_3
Z_3 = [0, 1, 2]

Z_2 = [0, 1]

# Get all possible combinations of coefficients
coefficients = product(Z_2, repeat=5)
count = 0

# Iterate over all possible combinations
for coeffs in coefficients:
    a_4, a_3, a_2, a_1, a_0 = coeffs
    polynomial = f"{a_4}*x^4 + {a_3}*x^3 + {a_2}*x^2 + {a_1}*x + {a_0}"
    count += 1
    print(polynomial)

print(count)

In [ ]:
import itertools


Z_5 = [0, 1, 2, 3, 4]
Z_2 = [0, 1]
# Generate all possible coefficients
coefficients = list(itertools.product(Z_2, repeat=5))

coefficients = [c for c in coefficients if sum(c) >= 0]
count = 0
# Print the coefficients
for i, c in enumerate(coefficients):
    print(f"row # {i+1}: {c}")
    count+= 1


print(count)

row # 1: (0, 0, 0, 0, 0)
row # 2: (0, 0, 0, 0, 1)
row # 3: (0, 0, 0, 1, 0)
row # 4: (0, 0, 0, 1, 1)
row # 5: (0, 0, 1, 0, 0)
row # 6: (0, 0, 1, 0, 1)
row # 7: (0, 0, 1, 1, 0)
row # 8: (0, 0, 1, 1, 1)
row # 9: (0, 1, 0, 0, 0)
row # 10: (0, 1, 0, 0, 1)
row # 11: (0, 1, 0, 1, 0)
row # 12: (0, 1, 0, 1, 1)
row # 13: (0, 1, 1, 0, 0)
row # 14: (0, 1, 1, 0, 1)
row # 15: (0, 1, 1, 1, 0)
row # 16: (0, 1, 1, 1, 1)
row # 17: (1, 0, 0, 0, 0)
row # 18: (1, 0, 0, 0, 1)
row # 19: (1, 0, 0, 1, 0)
row # 20: (1, 0, 0, 1, 1)
row # 21: (1, 0, 1, 0, 0)
row # 22: (1, 0, 1, 0, 1)
row # 23: (1, 0, 1, 1, 0)
row # 24: (1, 0, 1, 1, 1)
row # 25: (1, 1, 0, 0, 0)
row # 26: (1, 1, 0, 0, 1)
row # 27: (1, 1, 0, 1, 0)
row # 28: (1, 1, 0, 1, 1)
row # 29: (1, 1, 1, 0, 0)
row # 30: (1, 1, 1, 0, 1)
row # 31: (1, 1, 1, 1, 0)
row # 32: (1, 1, 1, 1, 1)
32


In [ ]:
row31_pre = (-1, -4, -3, 0, 0)
row31 = np.mod(row31_pre, 2)
print(row31)

[1 0 1 0 0]


In [ ]:
row27un = (1, 1, 0, 1, 0)
row27sqr = np.polymul(row27un, row27un)
print(row27sqr)
_, row27_pre = np.polydiv(row27sqr, (1, 2, 1, 2, 2, 4))
print("Remainder: ", row27_pre)
row27 = np.mod(row27_pre, 2)
print(row27)

[1 2 1 2 2 0 1 0 0]
Remainder:  [-4.  1.  0.  0.]
[0. 1. 0. 0.]


In [ ]:
row14un = (0, 1, 1, 0, 1)
row14sqr = np.polymul(row14un, row14un)
print(row14sqr)
_, row14_pre = np.polydiv(row14sqr, (1, 2, 1, 2, 2, 4))
print(row14_pre)
row14 = np.mod(row14_pre, 2)
print(row14)

[1 2 1 2 2 0 1]
[-4.  1.]
[0. 1.]


In [ ]:
import numpy as np
import itertools

Z_2 = [0, 1]
Z_3 = [0, 1, 2]
num_coefficients = 5

card = pow(len(Z_2), num_coefficients)
# Define the modulus polynomial
modulus = np.array([1, 0, 1, 0, 0, 0], dtype= int)

# Generate all possible coefficients
coefficients = list(itertools.product(Z_2, repeat= num_coefficients))

# Generate the multiplicative table
table = np.zeros((card, card), dtype= object)
for i in range(card):
    for j in range(card):
        product = np.polymul(coefficients[i], coefficients[j])
        _, remainder = np.polydiv(product, modulus)
        if len(product) >= num_coefficients:
            res = np.mod(remainder,len(Z_2))
            res = [0]*(num_coefficients-len(res)) + list(res)
            table[i][j] = res
        else:
            res = np.mod(product, len(Z_2))
            res = [0]*(num_coefficients-len(res)) + list(res)
            table[i][j] = res

for i in range(card):
    for j in range(card):
        table[i][j] = [int(x) for x in table[i][j]]


for i in range(card):
    print(" row #", i+1, ": ", table[i][i])

 row # 1 :  [0, 0, 0, 0, 0]
 row # 2 :  [0, 0, 0, 0, 1]
 row # 3 :  [0, 0, 1, 0, 0]
 row # 4 :  [0, 0, 1, 0, 1]
 row # 5 :  [1, 0, 0, 0, 0]
 row # 6 :  [1, 0, 0, 0, 1]
 row # 7 :  [1, 0, 1, 0, 0]
 row # 8 :  [1, 0, 1, 0, 1]
 row # 9 :  [1, 0, 0, 0, 0]
 row # 10 :  [1, 0, 0, 0, 1]
 row # 11 :  [1, 0, 1, 0, 0]
 row # 12 :  [1, 0, 1, 0, 1]
 row # 13 :  [0, 0, 0, 0, 0]
 row # 14 :  [0, 0, 0, 0, 1]
 row # 15 :  [0, 0, 1, 0, 0]
 row # 16 :  [0, 0, 1, 0, 1]
 row # 17 :  [1, 0, 0, 0, 0]
 row # 18 :  [1, 0, 0, 0, 1]
 row # 19 :  [1, 0, 1, 0, 0]
 row # 20 :  [1, 0, 1, 0, 1]
 row # 21 :  [0, 0, 0, 0, 0]
 row # 22 :  [0, 0, 0, 0, 1]
 row # 23 :  [0, 0, 1, 0, 0]
 row # 24 :  [0, 0, 1, 0, 1]
 row # 25 :  [0, 0, 0, 0, 0]
 row # 26 :  [0, 0, 0, 0, 1]
 row # 27 :  [0, 0, 1, 0, 0]
 row # 28 :  [0, 0, 1, 0, 1]
 row # 29 :  [1, 0, 0, 0, 0]
 row # 30 :  [1, 0, 0, 0, 1]
 row # 31 :  [1, 0, 1, 0, 0]
 row # 32 :  [1, 0, 1, 0, 1]


In [ ]:
## Next, we want to find idempotents. To find them, we check the main diagonal only. Idempotents: e(x)^2 = e(x)

for i, c in enumerate(coefficients):
    print(f"{i+1}:    {c} --> {table[i][i]}")

count = 0

print("\n%%%%%%%%%%%%%%%% IDEMPOTENTS %%%%%%%%%%%%%%%%\n")
for i, c in enumerate(coefficients):
    if np.array_equal(c, table[i][i]):
        print(i+1, c, table[i][i])
        count += 1

  
print("Total number of idempotents: ", count)

1:    (0, 0, 0, 0, 0) --> [0, 0, 0, 0, 0]
2:    (0, 0, 0, 0, 1) --> [0, 0, 0, 0, 1]
3:    (0, 0, 0, 1, 0) --> [0, 0, 1, 0, 0]
4:    (0, 0, 0, 1, 1) --> [0, 0, 1, 0, 1]
5:    (0, 0, 1, 0, 0) --> [1, 0, 0, 0, 0]
6:    (0, 0, 1, 0, 1) --> [1, 0, 0, 0, 1]
7:    (0, 0, 1, 1, 0) --> [1, 0, 1, 0, 0]
8:    (0, 0, 1, 1, 1) --> [1, 0, 1, 0, 1]
9:    (0, 1, 0, 0, 0) --> [1, 0, 0, 0, 0]
10:    (0, 1, 0, 0, 1) --> [1, 0, 0, 0, 1]
11:    (0, 1, 0, 1, 0) --> [1, 0, 1, 0, 0]
12:    (0, 1, 0, 1, 1) --> [1, 0, 1, 0, 1]
13:    (0, 1, 1, 0, 0) --> [0, 0, 0, 0, 0]
14:    (0, 1, 1, 0, 1) --> [0, 0, 0, 0, 1]
15:    (0, 1, 1, 1, 0) --> [0, 0, 1, 0, 0]
16:    (0, 1, 1, 1, 1) --> [0, 0, 1, 0, 1]
17:    (1, 0, 0, 0, 0) --> [1, 0, 0, 0, 0]
18:    (1, 0, 0, 0, 1) --> [1, 0, 0, 0, 1]
19:    (1, 0, 0, 1, 0) --> [1, 0, 1, 0, 0]
20:    (1, 0, 0, 1, 1) --> [1, 0, 1, 0, 1]
21:    (1, 0, 1, 0, 0) --> [0, 0, 0, 0, 0]
22:    (1, 0, 1, 0, 1) --> [0, 0, 0, 0, 1]
23:    (1, 0, 1, 1, 0) --> [0, 0, 1, 0, 0]
24:    (1, 0, 1, 1, 

In [ ]:
table_strings = np.array(["" for i in range(card) for j in range(card)], dtype=object).reshape(card, card)
for i in range(card):
  for j in range(card):
    coeffs = table[i][j]
    table_strings[i][j] = f"{coeffs[0]}*x**4 + {coeffs[1]}*x**3 + {coeffs[2]}*x**2 + {coeffs[3]}*x + {coeffs[4]}"

print(table_strings)
print(table_strings.shape)

[['0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0'
  '0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0'
  '0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0' ...
  '0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0'
  '0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0'
  '0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0']
 ['0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0'
  '0*x**4 + 0*x**3 + 0*x**2 + 0*x + 1'
  '0*x**4 + 0*x**3 + 0*x**2 + 1*x + 0' ...
  '1*x**4 + 1*x**3 + 1*x**2 + 0*x + 1'
  '1*x**4 + 1*x**3 + 1*x**2 + 1*x + 0'
  '1*x**4 + 1*x**3 + 1*x**2 + 1*x + 1']
 ['0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0'
  '0*x**4 + 0*x**3 + 0*x**2 + 1*x + 0'
  '0*x**4 + 0*x**3 + 1*x**2 + 0*x + 0' ...
  '1*x**4 + 0*x**3 + 0*x**2 + 1*x + 0'
  '1*x**4 + 0*x**3 + 1*x**2 + 0*x + 0'
  '1*x**4 + 0*x**3 + 1*x**2 + 1*x + 0']
 ...
 ['0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0'
  '1*x**4 + 1*x**3 + 1*x**2 + 0*x + 1'
  '1*x**4 + 0*x**3 + 0*x**2 + 1*x + 0' ...
  '1*x**4 + 0*x**3 + 0*x**2 + 0*x + 1'
  '1*x**4 + 1*x**3 + 1*x**2 + 1*x + 0'
  '0*x**4 + 0*x**3 + 0*x**2 + 1*x + 1']
 ['0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0'


In [ ]:
from sympy import gcd
from sympy.abc import x
from sympy import Poly, gcd
import numpy as np

In [ ]:
import numpy as np

Z_2 = [0, 1]
num_coefficients = 5
card = len(Z_2) ** num_coefficients

coeffs = [''.join(str(i) for i in x) for x in itertools.product(Z_2, repeat=num_coefficients)]

f_x_strings = np.array(["" for i in range(card)], dtype=object).reshape(card)
for i in range(card):
    f_x_strings[i] = f"{coeffs[i][0]}*x**4 + {coeffs[i][1]}*x**3 + {coeffs[i][2]}*x**2 + {coeffs[i][3]}*x + {coeffs[i][4]}"

print(f_x_strings)
print(f_x_strings.shape)


['0*x**4 + 0*x**3 + 0*x**2 + 0*x + 0' '0*x**4 + 0*x**3 + 0*x**2 + 0*x + 1'
 '0*x**4 + 0*x**3 + 0*x**2 + 1*x + 0' '0*x**4 + 0*x**3 + 0*x**2 + 1*x + 1'
 '0*x**4 + 0*x**3 + 1*x**2 + 0*x + 0' '0*x**4 + 0*x**3 + 1*x**2 + 0*x + 1'
 '0*x**4 + 0*x**3 + 1*x**2 + 1*x + 0' '0*x**4 + 0*x**3 + 1*x**2 + 1*x + 1'
 '0*x**4 + 1*x**3 + 0*x**2 + 0*x + 0' '0*x**4 + 1*x**3 + 0*x**2 + 0*x + 1'
 '0*x**4 + 1*x**3 + 0*x**2 + 1*x + 0' '0*x**4 + 1*x**3 + 0*x**2 + 1*x + 1'
 '0*x**4 + 1*x**3 + 1*x**2 + 0*x + 0' '0*x**4 + 1*x**3 + 1*x**2 + 0*x + 1'
 '0*x**4 + 1*x**3 + 1*x**2 + 1*x + 0' '0*x**4 + 1*x**3 + 1*x**2 + 1*x + 1'
 '1*x**4 + 0*x**3 + 0*x**2 + 0*x + 0' '1*x**4 + 0*x**3 + 0*x**2 + 0*x + 1'
 '1*x**4 + 0*x**3 + 0*x**2 + 1*x + 0' '1*x**4 + 0*x**3 + 0*x**2 + 1*x + 1'
 '1*x**4 + 0*x**3 + 1*x**2 + 0*x + 0' '1*x**4 + 0*x**3 + 1*x**2 + 0*x + 1'
 '1*x**4 + 0*x**3 + 1*x**2 + 1*x + 0' '1*x**4 + 0*x**3 + 1*x**2 + 1*x + 1'
 '1*x**4 + 1*x**3 + 0*x**2 + 0*x + 0' '1*x**4 + 1*x**3 + 0*x**2 + 0*x + 1'
 '1*x**4 + 1*x**3 + 0*x**

In [ ]:
modulus = np.array([1, 0, 1, 0, 0, 0], dtype=int)
g = Poly(modulus[0]*x**5 + modulus[1]*x**4 + modulus[2]*x**3 + modulus[3]*x**2 + modulus[4]*x + modulus[5], x)

Units_Z2_x_m = set()

for i in range(len(f_x_strings)):
  f = Poly(f_x_strings[i], x)
  gfg = gcd(f, g)
  expr = str(gfg.expr)
  if (expr == '1' or expr == '0' or expr == '2'):
    Units_Z2_x_m.add(f.expr)

Units_Z2_x_m = list(Units_Z2_x_m)
print(Units_Z2_x_m)
print(len(Units_Z2_x_m))

[1, x**3 + x + 1, x**4 + x**3 + 1, x + 1, x**4 + x**2 + 1, x**3 + 1, x**4 + x**2 + x + 1, x**4 + x + 1, x**4 + x**3 + x + 1, x**4 + x**3 + x**2 + 1, x**2 + x + 1, x**4 + x**3 + x**2 + x + 1, x**4 + 1, x**3 + x**2 + 1]
14


In [ ]:
## https://math.stackexchange.com/questions/555532/irreducible-polynomial-in-z-p-x
## https://www.youtube.com/watch?v=82nmtNxPaXE